### ISSUE TITLE
About the Soft Spearman.

### ISSUE THREAD

**Issue by Weikang-sun** [Gonglab-THU/GeoStab#1]
The article employs a novel processing technique to train and evaluate DMS data of varying scales at a single level, which showcases an excellent innovation. I am highly intrigued by this approach and would greatly appreciate it if you could kindly share the DMS data processing methodology as well as the training code for the model with me.

**Comment by Gonglab-THU** [comment]
Hi Weikang, we've provided the training code and DMS data processing scripts in the `./train_code` directory. I hope this helps.
