### ISSUE TITLE
A smaller data_af.pt is needed to run run.py

### ISSUE THREAD

**Issue by Weikang-sun** [Gonglab-THU/GeoStab#2]
Hi, your work is very innovative. I tried to run GeoStab/train_code/fitness_model/run.py, but unfortunately I don't know how to generate data_af2.pt, nor do I know the structure of this file.
Could you provide an example of a DMS dataset, such as BRCA1_HUMAN_BRCT, or the code to generate data_af2.pt?

![屏幕截图 2024-09-15 102120](https://github.com/user-attachments/assets/f8952752-4e38-466b-8a64-46dad3be565d)

**Comment by Gonglab-THU** [comment]
I have added an example of BRCAL-HUMAN_BRCT data in the [folder](https://github.com/Gonglab-THU/GeoStab/blob/main/train_code/fitness_model/data_af2.pt).

**Comment by Weikang-sun** [comment]
This really work, thank you so much!
